module: KituraSessionRedis
author: IBM
github_url: https://github.com/Kitura-Next/Kitura-Session-Redis/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-Session-Redis.xcodeproj, -target, KituraSessionRedis, LIBRARY_SEARCH_PATHS=.build/debug]
